FROM python:3.10-slim-bullseye
WORKDIR /app
COPY requirements.txt .flaskenv ./
RUN apt update
RUN apt install nmap -y
RUN pip install --no-cache-dir -r requirements.txt
COPY static ./static
COPY templates ./templates
COPY app.py .
CMD ["gunicorn", "-b", ":5000", "app:app", "--timeout", "600"]